/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tutor_pro1041_sp24b2.view;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tutor_pro1041_sp24b2.model.ChiTietSP;
import tutor_pro1041_sp24b2.model.HoaDon;
import tutor_pro1041_sp24b2.model.HoaDonChiTiet;
import tutor_pro1041_sp24b2.repository.ChiTietSPRepository;
import tutor_pro1041_sp24b2.repository.HoaDonChiTietRepository;
import tutor_pro1041_sp24b2.repository.HoaDonRepository;
import tutor_pro1041_sp24b2.response.ChiTietSPResponse;
import tutor_pro1041_sp24b2.response.HoaDonChiTietResponse;

/**
 *
 * @author Syn
 */
public class BanHangView extends javax.swing.JPanel {
    // Hoa don
    HoaDonRepository hoaDonRepository;
    DefaultTableModel dtmHoaDon;
    // Danh sach san pham chi tiet
    ChiTietSPRepository chiTietSPRepository;
    DefaultTableModel dtmChiTietSanPham;
    // Gio hang
    HoaDonChiTietRepository hoaDonChiTietRepository;
    DefaultTableModel dtmHoaDonChiTiet;
    /**
     * Creates new form BanHangView
     */
    int idHoaDon = -1;
    public BanHangView() {
        initComponents();
        
        hoaDonRepository = new HoaDonRepository();
        dtmHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        fillTableHoaDon(hoaDonRepository.getAllChuaThanhToan());
        
        chiTietSPRepository = new ChiTietSPRepository();
        dtmChiTietSanPham = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        fillTableChiTietSanPham(chiTietSPRepository.getAll());
        
        hoaDonChiTietRepository = new HoaDonChiTietRepository();
        dtmHoaDonChiTiet = (DefaultTableModel) tblGioHang.getModel();
        
    }

    private void fillTableGiohang(ArrayList<HoaDonChiTietResponse> danhSach) {
        dtmHoaDonChiTiet.setRowCount(0);
        for(HoaDonChiTietResponse hdct: danhSach) {
            dtmHoaDonChiTiet.addRow(new Object[]{
               hdct.getId(),
               hdct.getIdChiTietSanPham(),
               hdct.getTenSanPham(),
               hdct.getTenMauSac(),
               hdct.getSoLuong(),
               hdct.getDonGia()
            });
        }
    }
    
    private void fillTableChiTietSanPham(ArrayList<ChiTietSPResponse> danhSach) {
        dtmChiTietSanPham.setRowCount(0);
        for(ChiTietSPResponse ctsp: danhSach) {
            dtmChiTietSanPham.addRow(new Object[]{
                ctsp.getId(),
                ctsp.getTenSanPham(),
                ctsp.getTenMauSac(),
                ctsp.getTenDongSanPham(),
                ctsp.getSoLuongTon(),
                ctsp.getGiaBan()
            });
        }
    }
    
    private void fillTableHoaDon(ArrayList<HoaDon> danhSach) {
        dtmHoaDon.setRowCount(0);
        for(HoaDon hoaDon: danhSach) {
            dtmHoaDon.addRow(new Object[]{
                hoaDon.getId(),
                hoaDon.getTenNguoiNhan(),
                hoaDon.getTinhTrang() == 0 ? "Chưa thanh toán" : "Đã thanh toán", 
                hoaDon.getNgayTao()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPhamChiTiet = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        tblTaoHoaDon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        tblThanhToan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Bán hàng");

        tblSanPhamChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Ten san pham", "Mau sac", "Dong san pham", "So luong ton", "Gia ban"
            }
        ));
        tblSanPhamChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamChiTietMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPhamChiTiet);
        if (tblSanPhamChiTiet.getColumnModel().getColumnCount() > 0) {
            tblSanPhamChiTiet.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Khach hang", "Tinh trang", "NgayTao"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDon);
        if (tblHoaDon.getColumnModel().getColumnCount() > 0) {
            tblHoaDon.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "IdChiTietSP", "Ten san pham", "Mau sac", "So luong", "Don gia"
            }
        ));
        jScrollPane3.setViewportView(tblGioHang);
        if (tblGioHang.getColumnModel().getColumnCount() > 0) {
            tblGioHang.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        tblTaoHoaDon.setText("Tạo hóa đơn");
        tblTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTaoHoaDonActionPerformed(evt);
            }
        });

        jLabel2.setText("Khách hàng");

        jLabel3.setText("Tên");

        jLabel4.setText("Số điện thoại");

        tblThanhToan.setText("Thanh toán");
        tblThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblThanhToanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Hóa đơn");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Giỏ hàng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Danh sách sản phẩm chi tiết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(tblTaoHoaDon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tblThanhToan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(56, 56, 56)
                                                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabel1)))
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tblTaoHoaDon)
                            .addComponent(tblThanhToan))))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTaoHoaDonActionPerformed
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        
        String tenKhachHang = txtTenKhachHang.getText();
        String soDienThoai = txtSoDienThoai.getText();
        hoaDonRepository.themHoaDon(new HoaDon(
                null,
                tenKhachHang,
                soDienThoai,
                dateFormat.format(date),
                null
        ));
        fillTableHoaDon(hoaDonRepository.getAllChuaThanhToan());
    }//GEN-LAST:event_tblTaoHoaDonActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int selectedIndex = tblHoaDon.getSelectedRow();
        idHoaDon = Integer.valueOf(tblHoaDon.getValueAt(selectedIndex, 0).toString());
        fillTableGiohang(hoaDonChiTietRepository.getAll(idHoaDon));
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tblSanPhamChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamChiTietMouseClicked
        int selectedIndex = tblSanPhamChiTiet.getSelectedRow();
        int soLuongMua = Integer.valueOf(JOptionPane.showInputDialog(this, "Nhap so luong mua"));
        
        // Cap nhat so luong san pham
        int idSanPhamChiTiet = Integer.valueOf(tblSanPhamChiTiet.getValueAt(selectedIndex, 0).toString());
        int soLuongHienTai = Integer.valueOf(tblSanPhamChiTiet.getValueAt(selectedIndex, 4).toString());
        int soLuongMoi = soLuongHienTai - soLuongMua;
        chiTietSPRepository.suaSoLuong(
                ChiTietSP
                        .builder()
                        .id(idSanPhamChiTiet)
                        .soLuongTon(soLuongMoi)
                        .build()
        );
        fillTableChiTietSanPham(chiTietSPRepository.getAll());
        
        // them vao gio hang
        int donGia = Integer.valueOf(tblSanPhamChiTiet.getValueAt(selectedIndex, 5).toString());
        hoaDonChiTietRepository.themHoaDonChiTiet(
                HoaDonChiTiet
                    .builder()
                    .idHoaDon(idHoaDon)
                    .idChiTietSanPham(idSanPhamChiTiet)
                    .soLuong(soLuongMua)
                    .donGia(donGia)
                .build()
        );
        fillTableGiohang(hoaDonChiTietRepository.getAll(idHoaDon));
    }//GEN-LAST:event_tblSanPhamChiTietMouseClicked

    private void tblThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblThanhToanActionPerformed
        hoaDonRepository.thanhToanHoaDon(HoaDon.builder().id(idHoaDon).build());
        fillTableHoaDon(hoaDonRepository.getAllChuaThanhToan());
        dtmHoaDonChiTiet.setRowCount(0);
    }//GEN-LAST:event_tblThanhToanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSanPhamChiTiet;
    private javax.swing.JButton tblTaoHoaDon;
    private javax.swing.JButton tblThanhToan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables

    
}
