/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tutor_pro1041_sp24b2.view;

import java.awt.CardLayout;

/**
 *
 * @author Syn
 */
public class HomePageView extends javax.swing.JFrame {
    CardLayout cardLayout;
    /**
     * Creates new form HomePageView
     */
    public HomePageView(String tenNhanVien) {
        initComponents();
        txtTenNhanVien.setText(tenNhanVien);
        cardLayout = (CardLayout) viewManHinh.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menu = new javax.swing.JPanel();
        btnQuanLySanPham = new javax.swing.JButton();
        btnBanHang = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JLabel();
        viewManHinh = new javax.swing.JPanel();
        banHangView1 = new tutor_pro1041_sp24b2.view.BanHangView();
        quanLySanPhamView1 = new tutor_pro1041_sp24b2.view.QuanLySanPhamView();
        hoaDonView1 = new tutor_pro1041_sp24b2.view.HoaDonView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setSize(new java.awt.Dimension(1000, 800));

        menu.setBackground(new java.awt.Color(204, 204, 255));
        menu.setMinimumSize(new java.awt.Dimension(195, 100));

        btnQuanLySanPham.setText("Quan ly san pham");
        btnQuanLySanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySanPhamActionPerformed(evt);
            }
        });

        btnBanHang.setText("Ban hang");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnHoaDon.setText("Hoa don");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Menu");

        jLabel2.setText("Nhan Vien");

        txtTenNhanVien.setText("Nhan Vien");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnQuanLySanPham))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBanHang)
                            .addComponent(btnHoaDon)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenNhanVien)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNhanVien))
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLySanPham)
                .addGap(80, 80, 80)
                .addComponent(btnBanHang)
                .addGap(85, 85, 85)
                .addComponent(btnHoaDon)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(menu);

        viewManHinh.setLayout(new java.awt.CardLayout());
        viewManHinh.add(banHangView1, "BanHang");
        viewManHinh.add(quanLySanPhamView1, "QuanLySanPham");
        viewManHinh.add(hoaDonView1, "HoaDon");

        jSplitPane1.setRightComponent(viewManHinh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLySanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySanPhamActionPerformed
        cardLayout.show(viewManHinh, "QuanLySanPham");
    }//GEN-LAST:event_btnQuanLySanPhamActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        cardLayout.show(viewManHinh, "BanHang");
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        cardLayout.show(viewManHinh, "HoaDon");
    }//GEN-LAST:event_btnHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private tutor_pro1041_sp24b2.view.BanHangView banHangView1;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnQuanLySanPham;
    private tutor_pro1041_sp24b2.view.HoaDonView hoaDonView1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menu;
    private tutor_pro1041_sp24b2.view.QuanLySanPhamView quanLySanPhamView1;
    private javax.swing.JLabel txtTenNhanVien;
    private javax.swing.JPanel viewManHinh;
    // End of variables declaration//GEN-END:variables
}
